insert into users (NAME, EMAIL) values ('Bilbo Baggins', 'b@email.com');
insert into users (NAME, EMAIL) values ('Frodo Baggins', 'f@email.com');
insert into users (NAME, EMAIL) values ('Cate', 'cate@email.com');
insert into users (NAME, EMAIL) values ('Diana', 'di@email.com');
insert into users (NAME, EMAIL) values ('Qwerty', 'qw@email.com');
insert into users (NAME, EMAIL) values ('Anne', 'a@email.com');
insert into users (NAME, EMAIL) values ('Barbie', 'b@email.com');
insert into users (NAME, EMAIL) values ('Charlie', 'c@email.com');
insert into users (NAME, EMAIL) values ('Dimitri', 'd@email.com');
insert into users (NAME, EMAIL) values ('Francis', 'f@email.com');
insert into users (NAME, EMAIL) values ('Gwen', 'g@email.com');
insert into users (NAME, EMAIL) values ('Harry', 'h@email.com');
insert into users (NAME, EMAIL) values ('Iris',  'i@email.com');
insert into users (NAME, EMAIL) values ('John',  'j@email.com');
insert into users (NAME, EMAIL) values ('Kate', 'k@email.com');